version : '3.8'

services:
  nginx:
    container_name: nginx-spring-cloud
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    networks:
      - main-webserver
      - sshmarket-net

networks:
  main-webserver:
    external: true
    name: "main-webserver"
  sshmarket-net:
    external: true
    name: "sshmarket-net"