FROM openjdk:17-jdk-alpine

ARG JAR_FILE=build/libs/*.jar

WORKDIR /myapp

COPY ${JAR_FILE} article-application.jar

ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul", "-jar","article-application.jar"]
