version: "3.8"

services:
  article-spring-app:
    container_name: article-spring-app
    image: j9a503.p.ssafy.io:8999/sshmarket-article:0.0
    environment:
      MYSQL_HOST: article-mysql
    expose:
      - "8083"
    networks:
      - sshmarket-net
      - sshmarket-article-net
networks:
  sshmarket-net:
    external: true
    name: "sshmarket-net"
  sshmarket-article-net:
    external: true
    name: "sshmarket-article-net"