version: "3.8"

services:
  trade-spring-app:
    container_name: trade-spring-app
    image: j9a503.p.ssafy.io:8999/sshmarket-trade:0.0
    environment:
      MYSQL_HOST: trade-mysql
    expose:
      - "8085"
    networks:
      - sshmarket-net
      - sshmarket-trade-net
networks:
  sshmarket-net:
    external: true
    name: "sshmarket-net"
  sshmarket-trade-net:
    external: true
    name: "sshmarket-trade-net"