version: "3.8"

services:
  member-spring-app:
    container_name: member-spring-app
    image: j9a503.p.ssafy.io:8999/sshmarket-member:0.0
    expose:
      - "8082"
    networks:
      - sshmarket-net
      - sshmarket-auth-net
networks:
  sshmarket-net:
    external: true
    name: "sshmarket-net"
  sshmarket-auth-net:
    external: true
    name: "sshmarket-auth-net"
